project_id = "wdqpmyhtyhlwkkdrkjwv"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false
